# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9"
    - name: List Xcode installations
      run: sudo ls -1 /Applications | grep "Xcode"
    - name: Select Xcode 15.1
      run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Prepare Code Coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/SieveCachePackageTests.xctest/Contents/MacOS/SieveCachePackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        fail_ci_if_error: true
        files: info.lcov
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: GratefulGuru/SieveCache
